
from django.urls import reverse
from django.utils.text import slugify

featured = [
    "🎮 ACTIVITIES",
    "🐢 ANIMALS & NATURE",
    "😃 FACES & EMOTIONS",
    "🏁 FLAGS",
    "🍏 FOOD & DRINK",
    "📷 OBJECTS",
    "👋 PEOPLE & BODY",
    "💯 SYMBOLS & SIGNS",
    "🚢 TRAVEL & PLACES",
    "Other Categories"
]

subfeatured = [['🎭 Arts & Crafts', '🎖️ Awards & Medals', '🎃 Events', '🎮 Games', '⚽ Sports'],
 ['🐸 Amphibians',
  '🦃 Birds',
  '💐 Flowers',
  '🐵 Mammals',
  '🐳 Marine Animals',
  '🌱 Plants',
  '🐊 Reptiles',
  '🐌 Small Animals'],
 ['😺 Cat Faces',
  '😕 Concerned Faces',
  '💩 Costumed Faces',
  '💋 Emotions',
  '🤠 Faces With Accessories',
  '🥰 Faces With Affection',
  '🤗 Faces With Hand(s)',
  '😋 Faces With Tongue',
  '🙈 Monkey Faces',
  '😤 Negative Faces',
  '🤐 Neutral & Skeptical Faces',
  '😌 Sleepy Faces',
  '😀 Smiling Faces',
  '😷 Unwell (Sick) Faces'],
 ['🇦🇨 Country Flags',
  '🏁 Common Flags',
  '🏴\U000e0067\U000e0062\U000e0065\U000e006e\U000e0067\U000e007f Subdivision Flags'],
 ['🍱 Asian Food',
  '🥢 Dishware',
  '🍼 Drinks',
  '🍇 Fruits',
  '🍞 Prepared Food (Meals)',
  '🦀 Seafood',
  '🍦 Sweet Food & Sweets',
  '🥑 Vegetables'],
 ['📔 Books & Papers',
  '👒 Clothing',
  '🔋 Computer',
  '🚪 Household',
  '🎥 Light & Video',
  '🔒 Locks',
  '✉️ Mails',
  '💉 Medicine',
  '💰 Money',
  '🎼 Music',
  '🎷 Musical Instruments',
  '💼 Office',
  '🚬 Other Objects',
  '📱 Phone',
  '⚗ Science',
  '🔇 Sound',
  '🔨 Tools',
  '✏️ Writing'],
 ['💆 Activities & Hobbies',
  '💪 Body Parts',
  '👪 Family',
  '👼 Fantasy & Fairy Tale',
  '👋 Fingers',
  '🙍 Gestures',
  '👏 Hands',
  '👶 People',
  '🗣 Person: Symbol',
  '👨\u200d⚕️ Professions & Roles',
  '🧘 Resting People',
  '🤺 Sportive People'],
 ['🔠 Alphanumeric Characters',
  '⬆️ Arrows',
  '🔀 Audio & Video Symbols',
  '♀ Gender',
  '▪️ Geometric Symbols',
  '1️⃣ Keycaps',
  '♾ Other Symbols',
  '🛐 Religion',
  '🏧 Signs',
  '⚠️ Warnings',
  '♈ Zodiac Signs'],
 ['🏟️ Buildings',
  '🏔️ Geographic (Geo)',
  '🛎️ Hotel',
  '🌍 Maps',
  '⛲ Other Places',
  '⛪ Religious Places',
  '🌑 Sky & Weather',
  '⌛ Time',
  '✈️ Transport: Air',
  '🚂 Transport: Ground',
  '⚓ Transport: Water'],
 ['🍁 Autumn',
  '🎉 Birthday & Celebration & Party',
  '🐂 Chinese New Year',
  '🐇 Easter',
  '🏁 Flags',
  '🦰 Hairstyle',
  '🎃 Halloween',
  '❤️ Hearts',
  '🏳️\u200d🌈 LGBT',
  '📑 Complete Emoji List',
  "💝 Love & Valentine's Day",
  '☪️ Ramadan',
  '🏫 School & University',
  '🛍️ Shopping Emoji',
  '🏽 Skin Tones',
  '🌷 Spring',
  '🌞 Summer',
  '🦃 Thanksgiving',
  '🔝 TOP 100',
  "⛄ Winter & Christmas & New Year's Eve"]]



def get_url(catname):
    slugified = slugify(catname)+"-emoji"
    reverse_link = reverse('category_detail', kwargs={'slug':slugified})
    return reverse_link

def get_featured_links():
    links = [list(map(get_url, x)) for x in subfeatured]
    zip1 = list(zip(subfeatured, links))
    zip2 = [dict(zip(x[0], x[1])) for x in zip1]
    return dict(zip(featured, zip2))
