# Generated by Django 3.1.12 on 2021-07-16 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emoji', '0012_emojiwiki_intro_html'),
        ('codetoemoji', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codepoints',
            name='emoji',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='emoji.emojiterra'),
        ),
    ]
