# Generated by Django 3.1.12 on 2021-07-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leanmoji', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(null=True)),
                ('meta_html', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(null=True)),
                ('meta_html', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='kaomoji',
            name='category',
            field=models.ManyToManyField(to='leanmoji.KCategory'),
        ),
        migrations.AddField(
            model_name='kaomoji',
            name='tag',
            field=models.ManyToManyField(to='leanmoji.KTag'),
        ),
    ]
