# Generated by Django 3.1.12 on 2021-07-26 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leanmoji', '0002_auto_20210721_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kaomoji',
            name='category',
        ),
        migrations.RemoveField(
            model_name='kaomoji',
            name='tag',
        ),
        migrations.DeleteModel(
            name='KCategory',
        ),
        migrations.DeleteModel(
            name='KTag',
        ),
    ]
