# Generated by Django 3.1.12 on 2021-07-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leanmoji', '0003_auto_20210726_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kaomoji',
            name='kaomoji',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='kaomoji',
            name='name',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='kaomoji',
            name='slug',
            field=models.SlugField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='kaomoji',
            name='url',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
