# Generated by Django 3.1.12 on 2021-07-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emoji', '0003_emojiterra_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emojiterra',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
