# Generated by Django 3.1.12 on 2021-07-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emoji', '0006_auto_20210711_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emojiterra',
            name='category',
        ),
        migrations.AddField(
            model_name='emojiterra',
            name='category',
            field=models.ManyToManyField(to='emoji.Category'),
        ),
    ]
