# Generated by Django 3.1.12 on 2021-07-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emoji', '0007_auto_20210712_0340'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmojiWiki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('emoji', models.CharField(max_length=1000)),
                ('url', models.CharField(max_length=1000)),
                ('slug', models.SlugField(unique=True)),
                ('example', models.TextField()),
                ('combination', models.TextField()),
                ('kaomoji', models.TextField()),
                ('unicode_info', models.TextField()),
                ('translation', models.TextField()),
                ('related', models.TextField()),
                ('img_apple', models.CharField(max_length=1000)),
                ('img_google', models.CharField(max_length=1000)),
                ('img_microsoft', models.CharField(max_length=1000)),
                ('img_facebook', models.CharField(max_length=1000)),
                ('img_messenger', models.CharField(max_length=1000)),
                ('img_twitter', models.CharField(max_length=1000)),
                ('img_whatsapp', models.CharField(max_length=1000)),
                ('img_samsung', models.CharField(max_length=1000)),
                ('img_lg', models.CharField(max_length=1000)),
                ('img_htc', models.CharField(max_length=1000)),
                ('img_mozilla', models.CharField(max_length=1000)),
                ('img_softbank', models.CharField(max_length=1000)),
                ('img_au_by_kddi', models.CharField(max_length=1000)),
                ('img_docomo', models.CharField(max_length=1000)),
                ('img_openmoji', models.CharField(max_length=1000)),
            ],
        ),
    ]
