# Generated by Django 3.1.12 on 2021-07-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emoji', '0008_emojiwiki'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emojiterra',
            name='unicode_codes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='emojiwiki',
            name='combination',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='emojiwiki',
            name='example',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='emojiwiki',
            name='img_apple',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='emojiwiki',
            name='img_au_by_kddi',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='emojiwiki',
            name='img_docomo',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='emojiwiki',
            name='img_facebook',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='emojiwiki',
            name='img_google',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='emojiwiki',
            name='img_htc',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='emojiwiki',
            name='img_lg',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='emojiwiki',
            name='img_messenger',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='emojiwiki',
            name='img_microsoft',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='emojiwiki',
            name='img_mozilla',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='emojiwiki',
            name='img_openmoji',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='emojiwiki',
            name='img_samsung',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='emojiwiki',
            name='img_softbank',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='emojiwiki',
            name='img_twitter',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='emojiwiki',
            name='img_whatsapp',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='emojiwiki',
            name='kaomoji',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='emojiwiki',
            name='related',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='emojiwiki',
            name='unicode_info',
            field=models.TextField(blank=True),
        ),
    ]
