# Generated by Django 3.1.12 on 2021-07-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emoji', '0009_auto_20210714_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emojiterra',
            name='unicode_codes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emojiwiki',
            name='combination',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emojiwiki',
            name='example',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emojiwiki',
            name='kaomoji',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emojiwiki',
            name='related',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emojiwiki',
            name='unicode_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
