# Generated by Django 3.1.12 on 2021-07-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emoji', '0010_auto_20210714_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='emojiwiki',
            name='intro',
            field=models.TextField(blank=True, null=True),
        ),
    ]
