# Generated by Django 3.1.12 on 2021-07-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emoji', '0011_emojiwiki_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='emojiwiki',
            name='intro_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
