# Generated by Django 3.1.12 on 2021-07-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emoji', '0012_emojiwiki_intro_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='emojiterra',
            name='twitter_sample',
            field=models.TextField(blank=True, null=True),
        ),
    ]
